[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "paris"
remappings = [
    "ethernaut/=lib/ethernaut/contracts/src/",
    "openzeppelin-contracts/=lib/ethernaut/contracts/lib/openzeppelin-contracts/",
    "openzeppelin-contracts-06/=lib/ethernaut/contracts/lib/openzeppelin-contracts-06/",
]

[profile.fallout]
src = 'script/solutions'
solc_version = '0.6.12'
evm_version = 'paris'
remappings = [
    "ethernaut/=lib/ethernaut/contracts/src/",
    "openzeppelin-contracts/=lib/ethernaut/contracts/lib/openzeppelin-contracts/",
    "openzeppelin-contracts-06/=lib/ethernaut/contracts/lib/openzeppelin-contracts-06/",
    "forge-std/=lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
